### ISSUE TITLE
Question about the new `ParsingError` exception

### ISSUE THREAD

**Issue by mrexodia** [0vercl0k/udmp-parser#11]
There's a few instances left that `printf` and `return false` instead of throwing an exception. Personally I don't think exceptions should be used at all, but if they are should it be used everywhere?

**Comment by 0vercl0k** [comment]
Ha yeah good catch - I brought it up while reviewing https://github.com/0vercl0k/udmp-parser/pull/6 but then I forgot / fell through the cracks.

Let me try to get rid of it and clean up the `printf`!

Cheers

**Comment by 0vercl0k** [comment]
I pushed https://github.com/0vercl0k/udmp-parser/compare/v4.0.2...v0.4.3 - lemme know if if this works for you / if I missed anything.

Cheers
