### ISSUE TITLE
Memory map doesn't include TEB pages

### ISSUE THREAD

**Issue by 0vercl0k** [0vercl0k/udmp-parser#2]
The `!address` function in Windbg reconstruct the memory maps including the TEB pages. I can modify the code to add those in the map as well, but I am not sure how Windbg knows their sizes:

```
18`ed1df000       18`ed1e0000        0`00001000 MEM_PRIVATE MEM_COMMIT                                     PEB        [720]
18`ed1e0000       18`ed1e2000        0`00002000 MEM_PRIVATE MEM_COMMIT                                     TEB        [~0; 720.38fc]
18`ed1e2000       18`ed1e4000        0`00002000 MEM_PRIVATE MEM_COMMIT                                     TEB        [~1; 720.2560]
18`ed1e4000       18`ed1e6000        0`00002000 MEM_PRIVATE MEM_COMMIT                                     TEB        [~2; 720.3c14]
18`ed1e6000       18`ed1e8000        0`00002000 MEM_PRIVATE MEM_COMMIT                                     TEB        [~3; 720.37b0]
```

Figure how this works - there's probably a region in the mem map and the TEB start addresses which might be enough to do the same.

**Comment by mrexodia** [comment]
The teb base should be in the thread structure somewhere. Not sure how the sizes are calculated, but I just hardcode it to 0x2000

**Comment by 0vercl0k** [comment]
Makes sense - and yes I do have the TEB start addresses already; I'll need to check on both x86/x64 if hardcoding this works fine :) Thanks for sharing!

Cheers

**Comment by 0vercl0k** [comment]
I took a look at this tonight - so actually it's not as bad as I thought; I thought I was missing the regions in the map but it's here.

Basically there's a big region that fits the PEB & the TEBs and WinDbg is smart enough to break it down and create holes.

Here is what `parser.exe` shows w/ `tests.zip/x86.ma.dmp`:
```
ed8000           eea000            12000  MEM_COMMIT MEM_PRIVATE   00 00 01 04...
```

And WinDbg breaks down the regions and create artificial 'holes':
```
ed8000   ed9000     1000 MEM_PRIVATE MEM_COMMIT        <unknown>  [................]
ed9000   edc000     3000 MEM_PRIVATE MEM_COMMIT        PEB        [1d78]
edc000   ee0000     4000 MEM_PRIVATE MEM_COMMIT        TEB        [~0; 1d78.3674]
ee0000   ee4000     4000 MEM_PRIVATE MEM_COMMIT        TEB        [~1; 1d78.658]
ee4000   ee8000     4000 MEM_PRIVATE MEM_COMMIT        TEB        [~2; 1d78.4a14]
ee8000   eea000     2000 MEM_PRIVATE MEM_COMMIT        TEB        [~3; 1d78.1270]
```

It seems like it hardcodes 0x4'000 per TEB and for the last one there's just a remaining hole of 0x2'000 bytes.

Anyways, I am happy with the current behavior and am closing this down. Feel free to re-open if I'm missing something!

Cheers
